### PR TITLE
LKE-12368 No more modal for preview

### PR DESCRIPTION
**Pull request by w8r**
[LKE-12368](https://linkurious.atlassian.net/browse/LKE-12368)
It should now take the full screen
export

[LKE-12368]: https://linkurious.atlassian.net/browse/LKE-12368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by w8r** [comment]
Screenshot 2024-07-30 at 17 24 01

**Comment by fantandrea** [comment]
@w8r @Leo-Nicolle can you add the `<base href="/">` in the `index.html` (please just copy/paste don't change it)? The missing directive is not compliant with the plugin architecture ([doc](https://docs.google.com/document/d/1rzs2mn757MGlLVYt7xfCkCwcIpwJ_57uvWK5pDSgEV4/edit#heading=h.abdnnfxqkmb))

**Comment by w8r** [comment]
@fantandrea like here #95?

**Comment by w8r** [comment]
@hsenbassam @aminerhanemi can we merge that?

**Review by davidrapin — APPROVED** [review]

**Pull request merged**
