### PR TITLE
Release 2.0.2 [ci:run]

### PR DESCRIPTION
**Pull request by linkurious-infra**
- added snapping doc (#33)
- Bump version and fix manifest name (#34)
- Fix background color (#35)
- Fixed plugin API version at 1.0.0 (#36)
- Custom Action fix (#39)
- Disabled dependency version check (#40)
- Bump to latest master dependencies [ci:run] [ci:build-prod]
- Fix plugin release and post release
- bump to 2.0.2
- Revert "Bump to latest master dependencies [ci:run] [ci:build-prod]"
- fix typo in package updater script
- fix ogma-parser version
- fix rest-client version
- make sure CI selects latest LKE dependencies from stable and not beta (ogma-parser & rest-client) (#44)
- Update .version
- Update .bumpversion.cfg

### CODE REVIEW

**Comment by enys** [comment]
@EricMallard where was the fix for the missing icons done ?

**Comment by EricMallard** [comment]
> @EricMallard where was the fix for the missing icons done ?

I do not know what you are talking about. Do you have a ticket?

**Comment by w8r** [comment]
@enys, in the frontend

**Comment by enys** [comment]
so why are we releasing the plugin ? :D

**Comment by w8r** [comment]
because we like delivering value

**Comment by enys** [comment]
> because we like delivering value

Yeah but this PR contains only automation fixes.  It was ver unclear that the fix for the missing custom icons was a pure frontend fix

**Review by enys — APPROVED** [review]

**Pull request merged**
